import json
from pydantic import BaseModel
from langchain_groq import ChatGroq
from graph_state import ReviewState, Finding
from agents.utils import build_code_context, build_precedent_context

class CriticOutput(BaseModel):
    verified_findings: list[Finding]

def critic_node(state: ReviewState) -> dict:
    llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.0)
    structured_llm = llm.with_structured_output(CriticOutput)
    
    code_ctx = build_code_context(state.get("code_chunks", []))
    precedent_ctx = build_precedent_context(state.get("precedents", []))
    
    # Collect all findings
    all_findings = (
        state.get("bug_risk_findings", []) + 
        state.get("convention_findings", []) + 
        state.get("test_coverage_findings", [])
    )
    
    if not all_findings:
        return {"verified_findings": []}
        
    findings_json = json.dumps([f.model_dump() for f in all_findings], indent=2)
    
    prompt = f"""You are an expert critic. You are given a list of findings generated by specialists for a PR review.
Your job is to verify EVERY finding against the actual retrieved chunk content.

## Diff under review
```diff
{state['diff']}
```

## Retrieved code chunks
{code_ctx or 'None retrieved.'}

## Retrieved PR precedents
{precedent_ctx or 'None retrieved.'}

## Findings to verify
```json
{findings_json}
```

Rules for verification:
1. Every finding MUST have valid citation IDs in `source_chunk_ids` — either [code:N]/[precedent:N]
   matching a retrieved chunk above, or [diff] referring to the diff under review.
2. For [code:N]/[precedent:N] citations: the cited chunk MUST exist in the retrieved context,
   and the claim MUST be supported by that chunk's actual content.
3. For [diff] citations: the claim MUST be verifiably true by reading the diff under review above.
4. If a finding is unsupported, hallucinates line numbers, or cites a chunk ID not present
   above, DROP IT entirely.
5. Return ONLY the list of findings that pass verification. Do not modify the valid findings.
"""
    result = structured_llm.invoke(prompt)
    return {"verified_findings": result.verified_findings}
